--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LoreDOTexe/FactionsUI
build-by-default: true
branches:
- main
projects:
  FactionsUI:
    path: ""
    libs:
      - src: https://poggit.pmmp.io/r/101416/libFormAPI_dev-3.phar
        version: 1.3.0
...
