--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LoreDOTexe/FactionsUI
build-by-default: true
branches:
- main
projects:
  FactionsUI:
    path: ""
    libs:
      - src: jojoe77777/FormAPI
...
